### ISSUE TITLE
Support for Xtreme FW?

### ISSUE THREAD

**Issue by jfxmedia** [playmean/fap-list#11]
I see it in the list, but currently not supported for any faps I've tried to build, for ClaraCrazy FW builds. 
https://github.com/ClaraCrazy/Flipper-Xtreme

Will this be supported?

**Comment by playmean** [comment]
Yeah, it's because my sdk builder cannot access xtreme firmware repository by now. Repository only available for signed in users. I need to implement this feature using API with auth token. Will do it when get free time.

**Comment by playmean** [comment]
It was unexpectedly fixed 😄
