### ISSUE TITLE
Screenshots do not appear on app page

### ISSUE THREAD

**Issue by akopachov** [playmean/fap-list#12]
I've added screenshots to `.flipcorg/gallery` directory [here](https://github.com/akopachov/flipper-zero_authenticator/tree/master/.flipcorg/gallery) but they still do not appear on the app page [here](https://flipc.org/akopachov/flipper-zero_authenticator?branch=master&root=totp)

Am I missed something?

**Comment by playmean** [comment]
They should be placed inside your app's root. In your case in `totp/.flipcorg/gallery`

**Comment by akopachov** [comment]
Works as charm! Thanks for clarification
