### ISSUE TITLE
Banner image is not getting displayed

### ISSUE THREAD

**Issue by akopachov** [playmean/fap-list#13]
I've added [banner image](https://github.com/akopachov/flipper-zero_authenticator/blob/master/totp/.flipcorg/banner.png) to .flipcorg folder but that image still is not getting displayed on app page [here](https://flipc.org/akopachov/flipper-zero_authenticator?branch=master&root=totp)

I also found that [this app](https://flipc.org/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading?branch=main) has the same issue.

**Comment by playmean** [comment]
Can you please show me your F12/Network tab Fetch/XHR entry for banner.png file?

**Comment by akopachov** [comment]
Ah, apologies, it was uBlock who blocks banner.png image. I guess it doesn't like image name.

![image](https://user-images.githubusercontent.com/1217426/235706618-13cf39e2-7a8b-4f69-84f6-e53216847b11.png)
