### ISSUE TITLE
Please link me

### ISSUE THREAD

**Issue by ZekePolarisBSH** [playmean/fap-list#16]
Please link me to where I can get the connector for Pokémon Trader.

**Comment by playmean** [comment]
What you mean?

https://flipc.org/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading

This?

**Comment by ZekePolarisBSH** [comment]
Yea, I am looking for the putting together the cable. I have an original cord but I don't know how should I go about it. I hope I made sense, reading this back I just confused my self.

**Comment by playmean** [comment]
I think you need to issue author at https://github.com/EstebanFuentealba/Flipper-Zero-Game-Boy-Pokemon-Trading

**Comment by ZekePolarisBSH** [comment]
Thank you, didn't understand at first. I close this
