### ISSUE TITLE
MIDI?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [playmean/fap-list#17]
Are you the maker of MIDI App? For some reason it isn't loading up. Stuck at forever loading.

**Comment by playmean** [comment]
No. I'm not a creator of any flipper apps. You can view original app's repository by clicking "Author" username at flipc.org apps's page

**Comment by ZekePolarisBSH** [comment]
I thought that but they claimed they didn't make the app, it said RogueMaster did but they said they didn't.

**Comment by playmean** [comment]
It's a RogueMaster's problem because he isn't specifying original author's name of apps.

**Comment by ZekePolarisBSH** [comment]
Sorry late reply, I thought it was RogueMaster, Idk why they lied to me saying it was your creation... You can re-close this if it opens
