### ISSUE TITLE
Where do I go for help with the website?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [playmean/fap-list#18]
https://flipc.org/Matthew78917/FlipperNested?branch=dev

I asked because this whole page isn't working so I can't even find the dev of the app.

**Comment by bettse** [comment]
I'm having the same problem for https://flipc.org/bettse/seader?branch=main

**Comment by ZekePolarisBSH** [comment]
Oh ok then it isn't just me

**Comment by playmean** [comment]
Fixed! Thank you!
