### ISSUE TITLE
Site showing an system error related to the database.

### ISSUE THREAD

**Issue by AlanLatte** [playmean/fap-list#21]
Hi, I found your great project, but the site showing an system error related to the database.
To add up, I didn't find your source code to try and help you fix the bug, but please note that the world STILL needs a flipper app marketplace!

`FATAL: the database system is in recovery mode (SQLSTATE=57P03)`

<img width="786" alt="image" src="https://github.com/playmean/fap-list/assets/47124982/d43d2376-6363-47b5-a806-019b7d8a3f18">

**Comment by playmean** [comment]
Fixed! There is an error related to free disk space, burned by dangling docker containers :) It will be fixed when all channels of firmware builders be rebuilt.

Thank you for report! ❤️
