### ISSUE TITLE
Xtreme wrong API version

### ISSUE THREAD

**Issue by ricsim** [playmean/fap-list#24]
I am using Xtreme stable. (XFW-0051_01092023.tgz) and when I download Apps from FapC, I get API mismatch.
FAP is for API 31, FW has 35.
Could you check the current Xtreme FW status?

**Comment by playmean** [comment]
Latest release of xtreme at https://github.com/Flipper-XFW/Xtreme-Firmware/releases/tag/XFW-0051_01092023 which has API 31.3

**Comment by ricsim** [comment]
See screenshot of about, and BLE Spam App just installed from flipc..org with xtreme release config.
![flipper-api](https://github.com/playmean/fap-list/assets/4521696/6ee4a98b-b5af-4ba0-96db-f4eadb222752)
![flipper-xtreme](https://github.com/playmean/fap-list/assets/4521696/194ae8e1-4ebe-43d4-901b-d8cf5b84877b)

**Comment by playmean** [comment]
This happened due to a change in the link to the firmware repository. Thank you for report. Fixed!
