### ISSUE TITLE
New fap categorise

### ISSUE THREAD

**Issue by polarikus** [playmean/fap-list#5]
Вышел релиз https://github.com/flipperdevices/flipperzero-firmware/releases/tag/0.78.1

В нём добавлены новые категории для FAPок. 
Не хотите ли вы добавить эти категории в flipc.org?

Новые категории в релизе: https://github.com/flipperdevices/flipperzero-firmware/pull/2438/files 
GPIO
USB 
Bluetooth
Media
NFC
Sub-GHz

**Comment by playmean** [comment]
Да, была мысль расширить список по ченджлогу, но я бы обратился к разработчикам прошивки и уточнил, может есть утвержденный список категорий. А далее по нему уже внедрить.

Спасибо за список

**Comment by playmean** [comment]
```
Sub-GHz
RFID 125
NFC
Infrared
GPIO
iButton
Bluetooth
USB
Games
Media
Tools
```

Получил такой список от одного из разработчика (список неточный, может измениться). Код уже в продакшене
